
package client.matrix;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MultiplyMatrixClient", targetNamespace = "matrix.client")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MultiplyMatrixClient {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws InterruptedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplyMatrices", targetNamespace = "matrix.client", className = "client.matrix.MultiplyMatrices")
    @ResponseWrapper(localName = "multiplyMatricesResponse", targetNamespace = "matrix.client", className = "client.matrix.MultiplyMatricesResponse")
    public String multiplyMatrices(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws InterruptedException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addServer", targetNamespace = "matrix.client", className = "client.matrix.AddServer")
    @ResponseWrapper(localName = "addServerResponse", targetNamespace = "matrix.client", className = "client.matrix.AddServerResponse")
    public void addServer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
