
package client.matrix;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MultiplyMatrixClientService", targetNamespace = "matrix.client", wsdlLocation = "http://localhost:1235/multiplyMatrices?wsdl")
public class MultiplyMatrixClientService
    extends Service
{

    private final static URL MULTIPLYMATRIXCLIENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.matrix.MultiplyMatrixClientService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = client.matrix.MultiplyMatrixClientService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:1235/multiplyMatrices?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:1235/multiplyMatrices?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MULTIPLYMATRIXCLIENTSERVICE_WSDL_LOCATION = url;
    }

    public MultiplyMatrixClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiplyMatrixClientService() {
        super(MULTIPLYMATRIXCLIENTSERVICE_WSDL_LOCATION, new QName("matrix.client", "MultiplyMatrixClientService"));
    }

    /**
     * 
     * @return
     *     returns MultiplyMatrixClient
     */
    @WebEndpoint(name = "MultiplyMatrixClientPort")
    public MultiplyMatrixClient getMultiplyMatrixClientPort() {
        return super.getPort(new QName("matrix.client", "MultiplyMatrixClientPort"), MultiplyMatrixClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultiplyMatrixClient
     */
    @WebEndpoint(name = "MultiplyMatrixClientPort")
    public MultiplyMatrixClient getMultiplyMatrixClientPort(WebServiceFeature... features) {
        return super.getPort(new QName("matrix.client", "MultiplyMatrixClientPort"), MultiplyMatrixClient.class, features);
    }

}
