
package matrix.multiply;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-03T17:35:58.781+02:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "ExecutionException", targetNamespace = "multiply.matrix")
public class ExecutionException_Exception extends Exception {
    
    private matrix.multiply.ExecutionException executionException;

    public ExecutionException_Exception() {
        super();
    }
    
    public ExecutionException_Exception(String message) {
        super(message);
    }
    
    public ExecutionException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ExecutionException_Exception(String message, matrix.multiply.ExecutionException executionException) {
        super(message);
        this.executionException = executionException;
    }

    public ExecutionException_Exception(String message, matrix.multiply.ExecutionException executionException, Throwable cause) {
        super(message, cause);
        this.executionException = executionException;
    }

    public matrix.multiply.ExecutionException getFaultInfo() {
        return this.executionException;
    }
}
