
package matrix.multiply;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-03T17:35:58.737+02:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "InterruptedException", targetNamespace = "multiply.matrix")
public class InterruptedException_Exception extends Exception {
    
    private matrix.multiply.InterruptedException interruptedException;

    public InterruptedException_Exception() {
        super();
    }
    
    public InterruptedException_Exception(String message) {
        super(message);
    }
    
    public InterruptedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InterruptedException_Exception(String message, matrix.multiply.InterruptedException interruptedException) {
        super(message);
        this.interruptedException = interruptedException;
    }

    public InterruptedException_Exception(String message, matrix.multiply.InterruptedException interruptedException, Throwable cause) {
        super(message, cause);
        this.interruptedException = interruptedException;
    }

    public matrix.multiply.InterruptedException getFaultInfo() {
        return this.interruptedException;
    }
}
