package matrix.multiply;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-03T17:35:58.856+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "MultiplyMatrixServiceService", 
                  wsdlLocation = "MultiplyMatrixService.wsdl",
                  targetNamespace = "multiply.matrix") 
public class MultiplyMatrixServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("multiply.matrix", "MultiplyMatrixServiceService");
    public final static QName MultiplyMatrixServicePort = new QName("multiply.matrix", "MultiplyMatrixServicePort");
    static {
        URL url = MultiplyMatrixServiceService.class.getResource("MultiplyMatrixService.wsdl");
        if (url == null) {
            url = MultiplyMatrixServiceService.class.getClassLoader().getResource("MultiplyMatrixService.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(MultiplyMatrixServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "MultiplyMatrixService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public MultiplyMatrixServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MultiplyMatrixServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiplyMatrixServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MultiplyMatrixServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MultiplyMatrixServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MultiplyMatrixServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns MultiplyMatrixService
     */
    @WebEndpoint(name = "MultiplyMatrixServicePort")
    public MultiplyMatrixService getMultiplyMatrixServicePort() {
        return super.getPort(MultiplyMatrixServicePort, MultiplyMatrixService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultiplyMatrixService
     */
    @WebEndpoint(name = "MultiplyMatrixServicePort")
    public MultiplyMatrixService getMultiplyMatrixServicePort(WebServiceFeature... features) {
        return super.getPort(MultiplyMatrixServicePort, MultiplyMatrixService.class, features);
    }

}
