package matrix.multiply;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-03T17:35:58.822+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "multiply.matrix", name = "MultiplyMatrixService")
@XmlSeeAlso({net.java.dev.jaxb.array.ObjectFactory.class, ObjectFactory.class})
public interface MultiplyMatrixService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "multiply.matrix/MultiplyMatrixService/multiplyRequest", output = "multiply.matrix/MultiplyMatrixService/multiplyResponse", fault = {@FaultAction(className = InterruptedException_Exception.class, value = "multiply.matrix/MultiplyMatrixService/multiply/Fault/InterruptedException"), @FaultAction(className = ExecutionException_Exception.class, value = "multiply.matrix/MultiplyMatrixService/multiply/Fault/ExecutionException")})
    @RequestWrapper(localName = "multiply", targetNamespace = "multiply.matrix", className = "matrix.multiply.Multiply")
    @WebMethod
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "multiply.matrix", className = "matrix.multiply.MultiplyResponse")
    public java.util.List<net.java.dev.jaxb.array.DoubleArray> multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<net.java.dev.jaxb.array.DoubleArray> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<net.java.dev.jaxb.array.DoubleArray> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4
    ) throws InterruptedException_Exception, ExecutionException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "multiply.matrix/MultiplyMatrixService/getPoolSizeRequest", output = "multiply.matrix/MultiplyMatrixService/getPoolSizeResponse")
    @RequestWrapper(localName = "getPoolSize", targetNamespace = "multiply.matrix", className = "matrix.multiply.GetPoolSize")
    @WebMethod
    @ResponseWrapper(localName = "getPoolSizeResponse", targetNamespace = "multiply.matrix", className = "matrix.multiply.GetPoolSizeResponse")
    public int getPoolSize();

    @Action(input = "multiply.matrix/MultiplyMatrixService/setPoolSizeRequest", output = "multiply.matrix/MultiplyMatrixService/setPoolSizeResponse")
    @RequestWrapper(localName = "setPoolSize", targetNamespace = "multiply.matrix", className = "matrix.multiply.SetPoolSize")
    @WebMethod
    @ResponseWrapper(localName = "setPoolSizeResponse", targetNamespace = "multiply.matrix", className = "matrix.multiply.SetPoolSizeResponse")
    public void setPoolSize(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
