
package matrix.multiply;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.java.dev.jaxb.array.DoubleArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MultiplyMatrixImpl", targetNamespace = "multiply.matrix")
@XmlSeeAlso({
    matrix.multiply.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface MultiplyMatrixImpl {


    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.java.dev.jaxb.array.DoubleArray>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "multiply.matrix", className = "matrix.multiply.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "multiply.matrix", className = "matrix.multiply.MultiplyResponse")
    public List<DoubleArray> multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        List<DoubleArray> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<DoubleArray> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

}
