
package matrix.multiply;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MultiplyMatrixImplService", targetNamespace = "multiply.matrix", wsdlLocation = "http://0.0.0.0:1234/MultiplyMatrixService?wsdl")
public class MultiplyMatrixImplService
    extends Service
{

    private final static URL MULTIPLYMATRIXIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(matrix.multiply.MultiplyMatrixImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = matrix.multiply.MultiplyMatrixImplService.class.getResource(".");
            url = new URL(baseUrl, "http://0.0.0.0:1234/MultiplyMatrixService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://0.0.0.0:1234/MultiplyMatrixService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MULTIPLYMATRIXIMPLSERVICE_WSDL_LOCATION = url;
    }

    public MultiplyMatrixImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiplyMatrixImplService() {
        super(MULTIPLYMATRIXIMPLSERVICE_WSDL_LOCATION, new QName("multiply.matrix", "MultiplyMatrixImplService"));
    }

    /**
     * 
     * @return
     *     returns MultiplyMatrixImpl
     */
    @WebEndpoint(name = "MultiplyMatrixImplPort")
    public MultiplyMatrixImpl getMultiplyMatrixImplPort() {
        return super.getPort(new QName("multiply.matrix", "MultiplyMatrixImplPort"), MultiplyMatrixImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultiplyMatrixImpl
     */
    @WebEndpoint(name = "MultiplyMatrixImplPort")
    public MultiplyMatrixImpl getMultiplyMatrixImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("multiply.matrix", "MultiplyMatrixImplPort"), MultiplyMatrixImpl.class, features);
    }

}
