
package matrix.multiply;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-03T17:35:58.572+02:00
 * Generated source version: 3.0.1
 * 
 */
public final class MultiplyMatrixService_MultiplyMatrixServicePort_Client {

    private static final QName SERVICE_NAME = new QName("multiply.matrix", "MultiplyMatrixServiceService");

    private MultiplyMatrixService_MultiplyMatrixServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MultiplyMatrixServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MultiplyMatrixServiceService ss = new MultiplyMatrixServiceService(wsdlURL, SERVICE_NAME);
        MultiplyMatrixService port = ss.getMultiplyMatrixServicePort();  
        
        {
        System.out.println("Invoking multiply...");
        java.util.List<net.java.dev.jaxb.array.DoubleArray> _multiply_arg0 = null;
        java.util.List<net.java.dev.jaxb.array.DoubleArray> _multiply_arg1 = null;
        int _multiply_arg2 = 0;
        int _multiply_arg3 = 0;
        int _multiply_arg4 = 0;
        try {
            java.util.List<net.java.dev.jaxb.array.DoubleArray> _multiply__return = port.multiply(_multiply_arg0, _multiply_arg1, _multiply_arg2, _multiply_arg3, _multiply_arg4);
            System.out.println("multiply.result=" + _multiply__return);

        } catch (InterruptedException_Exception e) { 
            System.out.println("Expected exception: InterruptedException has occurred.");
            System.out.println(e.toString());
        } catch (ExecutionException_Exception e) { 
            System.out.println("Expected exception: ExecutionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPoolSize...");
        int _getPoolSize__return = port.getPoolSize();
        System.out.println("getPoolSize.result=" + _getPoolSize__return);


        }
        {
        System.out.println("Invoking setPoolSize...");
        int _setPoolSize_arg0 = 0;
        port.setPoolSize(_setPoolSize_arg0);


        }

        System.exit(0);
    }

}
